#!/bin/bash
[% c("var/set_default_env") -%]
[% pc(c('var/compiler'), 'var/setup', { compiler_tarfile => c('input_files_by_name/' _ c('var/compiler')) }) %]
distdir=/var/tmp/dist/[% project %]
mkdir -p $distdir
mkdir -p /var/tmp/build
tar -C /var/tmp/build -xf [% project %]-[% c('version') %].tar.[% c('compress_tar') %]
cd /var/tmp/build/[% project %]-[% c('version') %]
export CPPFLAGS=-DZSTD_MULTITHREAD
export CC=[% c("var/CC") %]
export CFLAGS="-Oz"
make -C lib -j[% c("num_procs") %] PREFIX=$distdir install
# Only need static libraries
rm $distdir/lib/libzstd.so*
cp COPYING LICENSE $distdir/
cd /var/tmp/dist
[% c('tar', {
        tar_src => [ project ],
        tar_args => '-caf ' _ dest_dir _ '/' _ c('filename'),
    }) %]
