#!/bin/bash

[% c("var/set_default_env") -%]
python3 -m pip download -d glean-wheels -v glean_parser==[% c("version") %]
[% c('tar', {
    tar_src => [ 'glean-wheels' ],
    tar_args => '-cJf ' _ dest_dir _ '/' _ c('filename'),
  }) %]
