#!/bin/bash
[% c("var/set_default_env") -%]
tar -xf [% project %]-[% c("version") %].tar.[% c('compress_tar') %]
mv [% project %]-[% c("version") %] clang-source
[% c('tar', {
        tar_src => [ 'clang-source' ],
        tar_args => '-caf ' _ dest_dir _ '/' _ c('filename'),
    }) %]
