#!/bin/bash
set -e
script_dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source "$script_dir/functions"
source "$script_dir/set-config.blog"

var_is_defined blog_publish_user blog_directory

content_dir="$blog_directory/content/blog"
test -d "$content_dir" || exit_error "$content_dir is not a direcotry"

blog_dir="$content_dir/new-release-tor-browser-"$(echo $tbb_version | sed 's/\.//g')

test -d "$blog_dir" && exit_error "$blog_dir already exists"

mkdir "$blog_dir"
echo "Created directory $blog_dir"

if test "$tbb_version_type" = "release"
then
  lead=../../../assets/static/images/blog/tor-browser-stable.png
else
  lead=../../../assets/static/images/blog/tor-browser-alpha.png
fi
ln -s "$lead" "$blog_dir/lead.png"
echo "Created $blog_dir/lead.png -> $lead"


if test "$tbb_version_type" = "release"
then
  title="New Release: Tor Browser $tbb_version"
  download_page='https://www.torproject.org/download/'
else
  title="New Alpha Release: Tor Browser $tbb_version"
  download_page='https://www.torproject.org/download/alpha/'
fi

contents_lr="$blog_dir/contents.lr"
cat > "$contents_lr" << EOF
title: $title
---
pub_date: $(date +%Y-%m-%d)
---
_discoverable: no
---
author: $blog_publish_user
---
categories:

applications
releases
---
summary: Tor Browser $tbb_version is now available from the Tor Browser download page and also from our distribution directory.
---
body:
Tor Browser $tbb_version is now available from the [Tor Browser download page]($download_page) and also from our [distribution directory](https://www.torproject.org/dist/torbrowser/$tbb_version/).

This version includes important [security updates](https://www.mozilla.org/en-US/security/advisories/) to Firefox.

__Important__: this release is part of the legacy channel, meant to extend the support for Windows 7/8/8.1 and macOS 10.12-10.14.
If your OS is not one of these, you should download the latest stable from the 15.0 series instead.

__Further updates to this 13.5.x legacy channel are not guaranteed: please upgrade to 15.0.x as soon as possible.__

## Send us your feedback

If you find a bug or have a suggestion for how we could improve this release, [please let us know](https://support.torproject.org/misc/bug-or-feedback/).

## Full changelog

EOF

$script_dir/../changelog-format-blog-post >> "$contents_lr"
echo "Created $contents_lr"
