#!/bin/bash

# This script runs `make dmg2mar-release` or `make dmg2mar-alpha`, and assumes
# that the final signed dmgs are deployed to the normal signed directory.
# It should be run after `gatekeeper-bundling.sh`.

set -e

script_dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source "$script_dir/functions"

cd "$script_dir/../.."

# some initial checks to make sure directories and file counts are as expected...

test -d "$signed_version_dir" || \
  exit_error "$signed_version_dir does not exist"

# before building converting the dmg to a mar

make $SIGNING_PROJECTNAME-dmg2mar-$tbb_version_type
