#!/bin/bash

# Remove current tbb version from macos-signer. You should run this
# when all signing has been done.

set -e
script_dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source "$script_dir/functions"

var_is_defined ssh_host_macos_signer tbb_version

ssh "$ssh_host_macos_signer" 'bash -s' << EOF
  test -n "$tbb_version" && rm -Rfv ~/"$tbb_version"
EOF
