#!/bin/bash
set -e

export YUBIHSM_PKCS11_CONF=~/yubihsm_pkcs11.conf

read -sp "Enter passphrase: " pass
echo
for i in `find . -name "*.exe" -print`
do
  /home/yubihsm/osslsigncode/osslsigncode \
                 -pkcs11engine /usr/lib/engines/engine_pkcs11.so \
                 -pkcs11module /usr/local/lib/yubihsm_pkcs11.so \
                 -pass "$pass" \
                 -h sha256 \
                 -certs /home/yubihsm/tpo-cert.crt \
                 -key 1c40 \
                 $i $i-signed
done
unset pass
rename -f 's/-signed//' *-signed
