#!/bin/bash

read -sp "Enter passphrase: " pass
for i in `find . -name "*.dmg" -o -name "*.exe" -o -name "*.tar.xz" -o -name "*.txt" -o -name "*.zip" -o -name "*.tar.gz" -o -name "*.apk" | sort`
do
  if test -f "$i.asc"
  then
    echo "Removing $i.asc"
    rm -f "$i.asc"
  fi
  echo "Signing $i"
  echo "$pass" | gpg -absu 0xe53d989a9e2d47bf! --passphrase-fd 0 $i
  test $? || echo "Signing $i failed"
done
