#!/bin/bash
set -e
script_dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source "$script_dir/functions"

var_is_defined ssh_host_staticiforme

generate_config

rsync $rsync_options "$script_dir/" "$ssh_host_staticiforme:signing-$SIGNING_PROJECTNAME-$tbb_version_type/"
