#!/bin/bash
set -e
script_dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source "$script_dir/functions"

var_is_defined ssh_host_linux_signer

rsync $rsync_options "$ssh_host_linux_signer:$SIGNING_PROJECTNAME-$tbb_version-macos-signed/" "$macos_rcodesign_signed_tar_dir/"
