#!/bin/bash
[% c("var/set_default_env") -%]
tar -xf [% project %]-[% c("version") %].tar.[% c('compress_tar') %]
mv [% project %]-[% c("version") %] [% project %]-[% c("step") %]
[% SET tar_source = project _ '-' _ c('step') -%]
[% c('tar', {
        tar_src => [ tar_source ],
        tar_args => '-czf ' _ dest_dir _ '/' _ c('filename'),
    }) %]
