#!/bin/bash
[% c("var/set_default_env") -%]

distdir=$rootdir/[% project %]
mkdir -p $distdir
cd $distdir

# Command line tools
mkdir -p cmdline-tools
unzip -qq $rootdir/[% c("input_files_by_name/android_commandlinetools") %] -d cmdline-tools
mv cmdline-tools/cmdline-tools cmdline-tools/[% c("var/commandlinetools_version_string") %]

# Build tools
mkdir build-tools
unzip -qq $rootdir/[% c("input_files_by_name/build_tools") %] -d build-tools
mv build-tools/[% c("var/android_release_dir") %] build-tools/[% c("version") %]

# Platforms
mkdir platforms
unzip -qq $rootdir/[% c("input_files_by_name/platform-36") %] -d platforms
unzip -qq $rootdir/[% c("input_files_by_name/platform-36.1") %] -d platforms
# This platform version is not detected without this file for some reason.
# Even `sdkmanager --list` fails without it.
# My hypothesis is that some tools expect the API level to be an integer.
# After installing this platform package with sdkmanager, we found this was the
# only file we were missing, and adding it fixes the build errors.
# Normally, it should not be needed. So, when upgrading, do not add its
# package.xml, unless you encounter the same bug.
mv $rootdir/platform-36.1-package.xml platforms/android-36.1/package.xml

# Platform tools
unzip -qq $rootdir/[% c("input_files_by_name/platform_tools") %]

# Placeholder for the NDK, as some projects expect the NDK to be in
# $ANDROID_HOME/ndk/<ndk-version>.
# We will add a symlink to the actual NDK in the setup when available.
mkdir ndk

# That's a quirk required by GeckoView but let's have it here instead of in the
# project's build script
mkdir emulator
touch emulator/emulator
chmod +x emulator/emulator

cd $rootdir
[% c('tar', {
    tar_src => [ project ],
    tar_args => '-caf ' _ dest_dir _ '/' _ c('filename'),
  }) %]
