#!/bin/bash
[% c("var/set_default_env") -%]

[% IF c("var/linux") -%]
  [% pc(c('var/compiler'), 'var/setup', { compiler_tarfile => c('input_files_by_name/' _ c('var/compiler')) }) %]
[% END -%]

distdir=/var/tmp/dist/[% project %]
mkdir -p $distdir
tar xf [% c('input_files_by_name/python') %]
cd Python-[% c('version') %]
./configure --prefix=$distdir --enable-optimizations
make -j[% c("num_procs") %]
make prefix=$distdir install
cd /var/tmp/dist
[% c('tar', {
	tar_src => 'python',
	tar_args => '-caf ' _ dest_dir _ '/' _ c('filename'),
    }) %]
