#!/bin/bash
[% c("var/set_default_env") -%]
distdir=/var/tmp/dist/openssl
mkdir -p /var/tmp/build
tar -C /var/tmp/build -xf openssl-[% c('version') %].tar.[% c('compress_tar') %]
cd /var/tmp/build/openssl-[% c('version') %]
export SOURCE_DATE_EPOCH='[% c("timestamp") %]'
./Configure --prefix="$distdir" -shared enable-ec_nistp_64_gcc_128 linux-x86_64
make -j[% c("num_procs") %]
make -j[% c("num_procs") %] install
cd /var/tmp/dist
[% c('tar', {
        tar_src => [ 'openssl' ],
        tar_args => '-czf ' _ dest_dir _ '/' _ c('filename'),
    }) %]
