#!/usr/bin/env bash

TBB_START_PROG="$(grep '^X-[% c("var/ProjectName") %]-ExecShell' $1 | tail -1 | sed 's/^X-[% c("var/ProjectName") %]-ExecShell=//' | sed 's/%.//')"

shift

if [ "$#" -ge 1 ]
then
  echo "Launching '${TBB_START_PROG} $@'..."
else
  echo "Launching '${TBB_START_PROG}'..."
fi

${TBB_START_PROG} "$@"
