#!/bin/bash
# This script will sign the aab given as argument, as signed.aab in the
# current directory, using the key config from generate-android-signing-key

set -e
script_dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
set_config_only=1
source "$script_dir/generate-android-signing-key"

if test "$#" -ne 1; then
  echo "Wrong number of arguments" >&2
  exit 1
fi

jarsigner -keystore "$script_dir/android-key/${key_alias}-private.p12" \
          -storepass "${key_password}" -signedjar signed.aab -verbose \
          "$1" "${key_alias}"
echo "Signed $1 in signed.aab"
