#!/bin/bash
[% c("var/set_default_env") -%]
distdir=/var/tmp/dist/[% project %]

OUTDIR='[% dest_dir _ "/" _ c("filename") %]'
mkdir -p $OUTDIR
mkdir -p "$distdir"

export SOURCE_DATE_EPOCH='[% c("timestamp") %]'
umask 0022

[% IF c("var/build_deb_pkg") -%]
  cd $distdir
  project_dir=[% c("var/system_pkg/pkg_name") %]-[% c("var/system_pkg/pkg_version") %]
  mkdir "$project_dir"
  cp -a $rootdir/Makefile $rootdir/[% c("var/system_pkg/pkg_name") %].desktop "$project_dir"
  [% c('tar', {
        tar_src => [ '$project_dir' ],
        tar_args => '-cJf ' _ c("var/system_pkg/pkg_name") _ '_' _ c("var/system_pkg/pkg_version") _ '.orig.tar.xz',
       }) %]

  cd "$project_dir"
  mv $rootdir/debian .
  chmod +x debian/docs debian/rules
  mkdir debian/source
  echo -n '3.0 (quilt)' > debian/source/format


  function extract_src_tar {
    src_tar="$1"
    deb_arch="$2"
    mkdir $deb_arch
    tar -C $deb_arch --strip-components=1 -xf "$src_tar"
    cp "$src_tar" \
      ../[% c("var/system_pkg/pkg_name") %]_[% c("var/system_pkg/pkg_version") %].orig-$deb_arch.tar.xz
  }
  [% IF c("var/browser-linux-x86_64") -%]
    extract_src_tar \
      $rootdir/[% c('input_files_by_name/linux-x86_64') %]/[% c("var/project-name") %]-linux-x86_64-[% c("version") %].tar.xz \
      amd64
  [% END -%]
  [% IF c("var/browser-linux-i686") -%]
    extract_src_tar \
      $rootdir/[% c('input_files_by_name/linux-x86_64') %]/[% c("var/project-name") %]-linux-i686-[% c("version") %].tar.xz \
      i386
  [% END -%]

  [% FOREACH deb_arch = c("var_p/system_pkg/deb_archs") -%]
    dpkg-buildpackage --unsigned-source --unsigned-changes --build=full --host-arch=[% deb_arch %]
    deb_file_name='[% c("var/system_pkg/pkg_name") %]_[% c("var/system_pkg/pkg_version") %]-[% c("var/system_pkg/pkg_revision") %]_[% deb_arch %].deb'
    dpkg-deb --info "../$deb_file_name"
    pushd ..
    mv -f "$deb_file_name" *.dsc *.orig.tar.xz *.debian.tar.xz "$OUTDIR/"
    popd
  [% END -%]

  cd ..
[% END %]

[% IF c("var/build_rpm_pkg") -%]

  cat > ~/.rpmmacros << EOF
  %clamp_mtime_to_source_date_epoch 1
  %use_source_date_epoch_as_buildtime 1
  %build_mtime_policy clamp_to_source_date_epoch
  %_buildhost localhost
EOF

  mkdir rpm
  cd rpm
  mkdir SPECS SOURCES
  cp -a $rootdir/[% c("var/system_pkg/pkg_name") %].spec SPECS
  cp -a $rootdir/Makefile $rootdir/[% c("var/system_pkg/pkg_name") %].desktop SOURCES/
  [% IF c("var/browser-linux-x86_64") -%]
    cp -a $rootdir/[% c('input_files_by_name/linux-x86_64') %]/[% c("var/project-name") %]-linux-x86_64-[% c("version") %].tar.xz \
      SOURCES/[% c("var/system_pkg/pkg_name") %]-linux-x86_64-[% c("var/system_pkg/pkg_version") %].tar.xz
  [% END -%]
  [% IF c("var/browser-linux-i686") -%]
    cp -a $rootdir/[% c('input_files_by_name/linux-i686') %]/[% c("var/project-name") %]-linux-i686-[% c("version") %].tar.xz \
      SOURCES/[% c("var/system_pkg/pkg_name") %]-linux-i686-[% c("var/system_pkg/pkg_version") %].tar.xz
  [% END -%]
  rpmdir=$(pwd)
  rpmbuild --define "_topdir $rpmdir" -v -bb SPECS/[% c("var/system_pkg/pkg_name") %].spec
  mv RPMS/*/*.rpm "$OUTDIR/"

[% END %]
