#!/bin/bash
[% c("var/set_default_env") -%]
[% IF c("var/linux") %]
  [% pc('gcc', 'var/setup', { compiler_tarfile => c('input_files_by_name/gcc'),
                              hardened_gcc => 0 }) %]
[% END -%]
distdir=/var/tmp/dist/[% project %]
tar -xf [% project %]-[% c('version') %].tar.xz
cd [% project %]-[% c('version') %]

./configure --prefix=$distdir
make -j[% c("num_procs") %]
make install

cd /var/tmp/dist
[% c('tar', {
        tar_src => [ project ],
        tar_args => '-caf ' _ dest_dir _ '/' _ c('filename'),
    }) %]
