#!/bin/bash
[% INCLUDE 'build_common' %]

echo "Starting the creation of the fat AAR $(date)"

tar -C $builddir -xf [% project %]-[% c('version') %].tar.[% c('compress_tar') %]


[% IF c("var/dev_artifacts") -%]
  mkdir -p $outdir/[% project %]/artifacts/armeabi-v7a
  mv $rootdir/[% c('input_files_by_name/geckoview_armv7') %]/artifacts/* $outdir/[% project %]/artifacts/armeabi-v7a
  mkdir -p $outdir/[% project %]/artifacts/arm64-v8a
  mv $rootdir/[% c('input_files_by_name/geckoview_aarch64') %]/artifacts/* $outdir/[% project %]/artifacts/arm64-v8a
  mkdir -p $outdir/[% project %]/artifacts/x86_64
  mv $rootdir/[% c('input_files_by_name/geckoview_x86_64') %]/artifacts/* $outdir/[% project %]/artifacts/x86_64
[% END -%]

# Specify the architectures we want to merge
export MOZ_ANDROID_FAT_AAR_ARCHITECTURES=armeabi-v7a,arm64-v8a,x86_64
export MOZ_ANDROID_FAT_AAR_ARMEABI_V7A=$rootdir/[% c('input_files_by_name/geckoview_armv7') %]/geckoview/target.maven.zip
export MOZ_ANDROID_FAT_AAR_ARM64_V8A=$rootdir/[% c('input_files_by_name/geckoview_aarch64') %]/geckoview/target.maven.zip
export MOZ_ANDROID_FAT_AAR_X86_64=$rootdir/[% c('input_files_by_name/geckoview_x86_64') %]/geckoview/target.maven.zip

cd $builddir/[% project %]-[% c("version") %]
cp $rootdir/mozconfig ./

# We still need to specify --base-browser-version due to bug 34005.
./mach configure \
  --with-base-browser-version=[% c("var/torbrowser_version") %] \
  --enable-update-channel=[% c("var/variant") %] \
  --with-branding=$branding_dir \
  [% IF !c("var/rlbox") -%]--without-wasm-sandboxed-libraries[% END %]

./mach build --verbose

[% INCLUDE 'build_ac_fenix' %]
