#!/bin/bash
[% c("var/set_default_env") -%]
[% pc('go', 'var/setup', { go_tarfile => c('input_files_by_name/go') }) %]
distdir=/var/tmp/dist/[% project %]
mkdir -p $distdir

tar -C /var/tmp/dist -xf [% c('input_files_by_name/go-licenses') %]
export PATH=$PATH:/var/tmp/dist/go-licenses

[% IF c("var/android") -%]
  [% pc(c('var/compiler'), 'var/setup', { compiler_tarfile => c('input_files_by_name/' _ c('var/compiler')) }) %]
  # We need to explicitly set CGO_ENABLED with Go 1.13.x as the Android build
  # breaks otherwise.
  export CGO_ENABLED=1
[% END -%]

mkdir -p /var/tmp/build
tar -C /var/tmp/build -xf [% project %]-[% c('version') %].tar.[% c('compress_tar') %]
cd /var/tmp/build/[% project %]-[% c('version') %]

tar -xf $rootdir/[% c('input_files_by_name/go_vendor') %]
[% IF c("var/windows") -%]
  pushd vendor/github.com/refraction-networking/conjure
  patch -p1 < $rootdir/conjure-pr-267.patch
  popd
[% END -%]

cd client
go build -ldflags '-s[% IF c("var/android") %] -checklinkname=0[% END %]' -tags 'protoreflect'
cp -a client[% IF c("var/windows") %].exe[% END %] $distdir/conjure-client[% IF c("var/windows") %].exe[% END %]

cd ..
cp -a README.md $distdir/README.CONJURE.md
go-licenses save ./client --save_path=$distdir/licenses

cd $distdir
[% c('tar', {
        tar_src => [ '.' ],
        tar_args => '-caf ' _ dest_dir _ '/' _ c('filename'),
    }) %]
