#!/bin/bash
[% c("var/set_default_env") -%]

unzip -qq $rootdir/[% c("input_files_by_name/ndk")%]
mv android-ndk-[% c("var/ndk_release") %] [% project %]
[% c('tar', {
    tar_src => [ project ],
    tar_args => '-caf ' _ dest_dir _ '/' _ c('filename'),
  }) %]
